### ISSUE TITLE
Set summary before persistInt()

### ISSUE THREAD

**Issue by Huulivoide** [vanniktech/VNTNumberPickerPreference#6]
Currently persisInt(mSelectedValue) is called before updateSummary()
this makes it impossible to to override the summary in
OnSharedPreferenceChangeListener.onSharedPreferenceChanged(SharedPreferences sp, String key)

**Comment by vanniktech** [comment]
There was an issue yes but it had nothing to do with the order of the function calls.

I've fixed the issue and also included a sample with de0fa6b27401527d3124f32b3e5ad9af1f010398

Also I've released version 0.1.2 of this library which will fix this issue.

Thanks for reporting it.

**Comment by vanniktech** [comment]
Argh I just found one issue with the Cancel button. Version 0.1.3 is the way to go. I'm sorry for this.

**Comment by Huulivoide** [comment]
The changes you have made have not fixed my problem.

Using setSummary(String) in OnSharedPreferenceChanged is still broken, due to the order of the function calls. persistInt(value) causes the OnShared... callbacks to get fired and executed, but then  any changes made to the summary in those callbacks will get overriden by updateSummary().

The following code snippet (can be used in SettingsActivity in the example app):
```java
public static class SettingsFragment extends PreferenceFragment implements SharedPreferences.OnSharedPreferenceChangeListener {
    private Preference mPreferenceCallback;

    @Override
    public void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.addPreferencesFromResource(R.xml.preferences);

        mPreferenceCallback = this.findPreference("preference_callback");
        getPreferenceManager().getSharedPreferences().registerOnSharedPreferenceChangeListener(this);
    }

    @Override
    public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String key)
    {
        if (key.equals("preference_callback"))
        {
            int val = sharedPreferences.getInt(key, 0);
            mPreferenceCallback.setSummary("My custom dynamic summary. The value is: " + val);
        }
    }
}
```

**Comment by vanniktech** [comment]
Oh okay you mean that. I'll fix that later. Also in version 0.1.1 the `setOnPreferenceChangeListener` did not work. I fixed that with 0.1.3. I'll also test that the `OnSharedPreferenceChangeListener` listener works.

**Comment by vanniktech** [comment]
Version 0.1.4 has been published now and the bug is fixed with 360bf7668b89a2fb9fc6f919c0080fee16ef9eb5. Sorry for the inconvenience.
